### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by manio143** [manio143/MultiPong#2]
- [x] Physics (currently buggy)
- [x] Server message handling
- [x] Common.NetworkClient
- [x] Messages serialization
- [x] Client message handling

In the future
- [ ] Proper Physics
- [ ] Virtual units & Scaling
- [ ] A Console client
